#!/bin/sh
#source activate egg36
#cd /home/ckervadec/EGG/
#python -m egg.zoo.basic_games.play --mode 'rf' --train_data "egg/zoo/basic_games/data_generation_scripts/example_reconstruction_input.txt" --validation_data "egg/zoo/basic_games/data_generation_scripts/example_reconstruction_input.txt" --n_attributes 5 --n_values 3 --n_epochs 200 --batch_size 512 --validation_batch_size 1000 --max_len 2 --vocab_size 200 --sender_hidden 256 --receiver_hidden 512 --sender_embedding 5 --receiver_embedding 30 --receiver_cell "gru" --sender_cell "gru" --lr 0.01 --print_validation_events --tensorboard --tensorboard_dir=./runs/basic_game_reco_m2_voc200/
#python -m egg.zoo.basic_games.play --game_type 'discri' --mode 'rf' --train_data "egg/zoo/basic_games/data_generation_scripts/example_discriminative_input.txt" --validation_data "egg/zoo/basic_games/data_generation_scripts/example_discriminative_input.txt" --n_values 3 --n_epochs 50 --batch_size 512 --validation_batch_size 10 --max_len 4 --vocab_size 100 --sender_hidden 256 --receiver_hidden 512 --sender_embedding 5 --receiver_embedding 30 --lr 0.01 --receiver_cell "gru" --sender_cell "gru" --random_seed 111 --print_validation_events --tensorboard --tensorboard_dir=./runs/basic_game_discri/
# CUDA_VISIBLE_DEVICE=0 python -m egg.zoo.sum_game.launcher
#CUDA_VISIBLE_DEVICE=0 python -m egg.zoo.sum_game.play --mode 'rf' --train_data egg/zoo/sum_game/data_generation_scripts/sum_dataset_standard_n100_train.txt --validation_data egg/zoo/sum_game/data_generation_scripts/sum_dataset_standard_n100_test.txt --n_range 100 --n_epochs 3000 --batch_size 512 --validation_batch_size 1000 --max_len 1 --vocab_size 199 --sender_hidden 256 --receiver_hidden 512 --sender_embedding 5 --receiver_embedding 30 --receiver_cell "gru" --sender_cell "gru" --lr 0.01 --tensorboard --tensorboard_dir=./runs/n100_rf_msg1_combi199_vocab199_nobalance_e0.12_seed2 --print_validation_events --loss xent --sender_entropy_coeff 0.12 --random_seed 2 --balanced_ce -1 --checkpoint_dir=./ckpt/n100_rf_msg1_combi199_vocab199_nobalance_e0.12_seed2 --checkpoint_freq 1000
#CUDA_VISIBLE_DEVICE=0 python -m egg.zoo.sum_game.play --mode 'rf' --train_data egg/zoo/sum_game/data_generation_scripts/sum_dataset_standard_n100_train.txt --validation_data egg/zoo/sum_game/data_generation_scripts/sum_dataset_standard_n100_test.txt --n_range 100 --n_epochs 3000 --batch_size 512 --validation_batch_size 1000 --max_len 1 --vocab_size 199 --sender_hidden 256 --receiver_hidden 512 --sender_embedding 5 --receiver_embedding 30 --receiver_cell "gru" --sender_cell "gru" --lr 0.01 --tensorboard --tensorboard_dir=./runs/n100_rf_msg1_combi199_vocab199_balance0.3_e0.12_seed2_sv --print_validation_events --loss xent --sender_entropy_coeff 0.12 --random_seed 2 --balanced_ce 0.3 --checkpoint_dir=./ckpt/n100_rf_msg1_combi199_vocab199_balance0.3_e0.12_seed2_sv --checkpoint_freq 1000
#CUDA_VISIBLE_DEVICE=0 python -m egg.zoo.sum_game.play --mode 'rf' --train_data egg/zoo/sum_game/data_generation_scripts/sum_dataset_standard_n100_train.txt --validation_data egg/zoo/sum_game/data_generation_scripts/sum_dataset_standard_n100_test.txt --n_range 100 --n_epochs 3000 --batch_size 512 --validation_batch_size 1000 --max_len 1 --vocab_size 99 --sender_hidden 256 --receiver_hidden 512 --sender_embedding 5 --receiver_embedding 30 --receiver_cell "gru" --sender_cell "gru" --lr 0.01 --tensorboard --tensorboard_dir=./runs/n100_rf_msg1_combi199_vocab199_nobalance_e0.12_seed2 --print_validation_events --loss xent --sender_entropy_coeff 0.14 --random_seed 2 --balanced_ce 0.3 --checkpoint_dir=./ckpt/n100_rf_msg1_combi199_vocab199_balance0.3_e0.12_seed2_sv --checkpoint_freq 1000
#CUDA_VISIBLE_DEVICE=0 python -m egg.zoo.sum_game.play --mode 'rf' --train_data egg/zoo/sum_game/data_generation_scripts/sum_dataset_standard_n20_train.txt --validation_data egg/zoo/sum_game/data_generation_scripts/sum_dataset_standard_n20_test.txt --n_range 20 --n_epochs 3000 --batch_size 512 --validation_batch_size 1000 --max_len 1 --vocab_size 39 --sender_hidden 256 --receiver_hidden 512 --sender_embedding 5 --receiver_embedding 30 --receiver_cell "gru" --sender_cell "gru" --lr 0.01 --tensorboard --tensorboard_dir=./runs/n20_rf_msg1_combi39_vocab39_balance0.6_e0.18_seed4 --print_validation_events --loss xent --sender_entropy_coeff 0.18 --random_seed 4 --balanced_ce 0.6 --checkpoint_dir=./ckpt/n20_rf_msg1_combi39_vocab39_balance0.6_e0.18_seed4 --checkpoint_freq 1000
#CUDA_VISIBLE_DEVICE=0 python -m egg.zoo.sum_game.play --mode 'rf' --train_data egg/zoo/sum_game/data_generation_scripts/sum_dataset_standard_n20_all.txt --validation_data egg/zoo/sum_game/data_generation_scripts/sum_dataset_standard_n20_all.txt --n_range 20 --n_epochs 0 --batch_size 512 --validation_batch_size 1000 --max_len 1 --vocab_size 39 --sender_hidden 256 --receiver_hidden 512 --sender_embedding 5 --receiver_embedding 30 --receiver_cell "gru" --sender_cell "gru" --lr 0.01 --print_validation_events --loss xent --sender_entropy_coeff 0.18 --random_seed 1 --balanced_ce 0.6 --load_from_checkpoint=./ckpt/all_n20_rf_msg1_combi39_vocab39_balance0.6_e0.18_seed1/final.tar  --analyse
#CUDA_VISIBLE_DEVICE=0 python -m egg.zoo.sum_game.play --mode 'rf' --train_data egg/zoo/sum_game/data_generation_scripts/sum_dataset_standard_n20_train.txt --validation_data egg/zoo/sum_game/data_generation_scripts/sum_dataset_standard_n20_test.txt --n_range 20 --n_epochs 0 --batch_size 512 --validation_batch_size 1000 --max_len 1 --vocab_size 39 --sender_hidden 256 --receiver_hidden 512 --sender_embedding 5 --receiver_embedding 30 --receiver_cell "gru" --sender_cell "gru" --lr 0.01 --print_validation_events --loss xent --sender_entropy_coeff 0.18 --random_seed 1 --balanced_ce 0.6 --load_from_checkpoint=./ckpt/n20_rf_msg1_combi39_vocab39_balance0.6_e0.18_seed4/1000.tar  --analyse
CUDA_VISIBLE_DEVICE=0 python -m egg.zoo.sum_game.play --mode 'rf' --train_data egg/zoo/sum_game/data_generation_scripts/sum_dataset_standard_n100_all.txt --validation_data egg/zoo/sum_game/data_generation_scripts/sum_dataset_standard_n100_inv_train.txt --n_range 100 --n_epochs 0 --batch_size 512 --validation_batch_size 1000 --max_len 1 --vocab_size 199 --sender_hidden 256 --receiver_hidden 512 --sender_embedding 5 --receiver_embedding 30 --receiver_cell "gru" --sender_cell "gru" --lr 0.01 --print_validation_events --loss xent --sender_entropy_coeff 0.12 --random_seed 1 --balanced_ce 0.3 --load_from_checkpoint=./ckpt/n100_rf_msg1_combi199_vocab199_balance0.3_e0.12_seed2_sv/final.tar  --analyse
#python -m egg.nest.nest_local --game egg.zoo.sum_game.play --sweep egg/nest/sum_hp.json --n_workers=1
